# Generated by Django 3.2.12 on 2022-02-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.CharField(max_length=12)),
                ('Sname', models.CharField(max_length=32)),
                ('Spwd', models.CharField(max_length=64)),
                ('Ssex', models.CharField(max_length=12)),
                ('SClass', models.CharField(max_length=32)),
            ],
        ),
    ]
