# Generated by Django 3.2.12 on 2022-02-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cno', models.CharField(max_length=12)),
                ('Cname', models.CharField(max_length=32)),
                ('Tno', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sno', models.CharField(max_length=12)),
                ('Cno', models.CharField(max_length=32)),
                ('Degree', models.IntegerField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Teacherinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tno', models.CharField(max_length=12)),
                ('Tname', models.CharField(max_length=32)),
                ('Tpwd', models.CharField(max_length=64)),
                ('Tsex', models.CharField(max_length=12)),
                ('Depart', models.CharField(max_length=32)),
            ],
        ),
    ]
