# Generated by Django 3.2.12 on 2022-02-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220227_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ccid', models.CharField(max_length=12)),
                ('Ccname', models.CharField(max_length=32)),
                ('Tid', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Tno',
            new_name='Tid',
        ),
        migrations.AddField(
            model_name='course',
            name='Ccname',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='Suser',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='Qscore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='Degree',
            field=models.IntegerField(),
        ),
    ]
