# Generated by Django 3.2.12 on 2022-02-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220227_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='Suser',
            new_name='Sphone',
        ),
        migrations.AddField(
            model_name='questions',
            name='Cid',
            field=models.CharField(default=10086, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherinfo',
            name='Tphone',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
