# Generated by Django 3.2.12 on 2022-02-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220227_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='Ssex',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')]),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='Tsex',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')]),
        ),
    ]
