# Generated by Django 3.2.12 on 2022-02-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220227_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='Ssex',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='Tsex',
            field=models.CharField(max_length=12),
        ),
    ]
