# Generated by Django 3.2.12 on 2022-02-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220227_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='Qcreate_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='QTreeName',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='questions',
            name='Qscore',
            field=models.FloatField(),
        ),
    ]
