# Generated by Django 3.2.12 on 2022-02-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220228_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Ccname',
        ),
        migrations.AddField(
            model_name='course',
            name='Cclassid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='Cid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='Tid',
            field=models.IntegerField(),
        ),
    ]
