# Generated by Django 3.2.12 on 2022-02-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220228_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_t',
            name='Ccid',
        ),
        migrations.AddField(
            model_name='class_t',
            name='Cclassid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class_t',
            name='Tid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='Cid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='Sid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='Sid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacherinfo',
            name='Tid',
            field=models.IntegerField(),
        ),
    ]
