# Generated by Django 3.2.12 on 2022-02-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220228_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Ccreate_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='Cend_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
